# Generated by Django 3.1 on 2020-08-15 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_name', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('i_frame', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ebook', models.URLField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('credentials', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('issue_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
